INSERT INTO stores (address) VALUES ('vul. Sobornaya, 51');
INSERT INTO stores (address) VALUES ('vul. Shevchenka, 2');
INSERT INTO stores (address) VALUES ('vul. Myru, 7');

INSERT INTO providers (name) VALUES ('Zara');
INSERT INTO providers (name) VALUES ('Top Secret');
INSERT INTO providers (name) VALUES ('Mango');

INSERT INTO goods (name, store_id) VALUES ('long dress', 1);
INSERT INTO goods (name, store_id) VALUES ('short dress', 1);
INSERT INTO goods (name, store_id) VALUES ('middle dress', 1);
INSERT INTO goods (name, store_id) VALUES ('long-sleeve shirt', 1);
INSERT INTO goods (name, store_id) VALUES ('short-sleeve shirt', 1);
INSERT INTO goods (name, store_id) VALUES ('wide trousers', 1);
INSERT INTO goods (name, store_id) VALUES ('narrow trousers', 1);
INSERT INTO goods (name, store_id) VALUES ('short trousers', 1);
INSERT INTO goods (name, store_id) VALUES ('sweater', 1);
INSERT INTO goods (name, store_id) VALUES ('pullover', 1);
INSERT INTO goods (name, store_id) VALUES ('long cardigan', 1);
INSERT INTO goods (name, store_id) VALUES ('sleeveless T-shirt', 2);
INSERT INTO goods (name, store_id) VALUES ('T-shirt', 2);
INSERT INTO goods (name, store_id) VALUES ('polo', 2);
INSERT INTO goods (name, store_id) VALUES ('long T-shirt', 2);
INSERT INTO goods (name, store_id) VALUES ('wide jeans', 2);
INSERT INTO goods (name, store_id) VALUES ('narrow jeans', 2);
INSERT INTO goods (name, store_id) VALUES ('high waist jeans', 2);
INSERT INTO goods (name, store_id) VALUES ('short shorts', 2);
INSERT INTO goods (name, store_id) VALUES ('middle shorts', 2);
INSERT INTO goods (name, store_id) VALUES ('long shorts', 2);
INSERT INTO goods (name, store_id) VALUES ('short skirt', 2);
INSERT INTO goods (name, store_id) VALUES ('middle skirt', 2);
INSERT INTO goods (name, store_id) VALUES ('long skirt', 3);
INSERT INTO goods (name, store_id) VALUES ('classic jacket', 3);
INSERT INTO goods (name, store_id) VALUES ('sport jacket', 3);
INSERT INTO goods (name, store_id) VALUES ('casual jacket', 3);
INSERT INTO goods (name, store_id) VALUES ('long coat', 3);
INSERT INTO goods (name, store_id) VALUES ('middle coat', 3);
INSERT INTO goods (name, store_id) VALUES ('short coat', 3);

INSERT INTO goods_providers (goods_id, provider_id) VALUES (1, 1);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (2, 3);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (3, 3);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (4, 2);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (5, 1);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (6, 2);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (7, 2);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (8, 1);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (9, 3);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (10, 1);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (11, 3);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (12, 2);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (13, 2);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (14, 1);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (15, 3);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (16, 1);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (17, 3);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (18, 3);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (19, 2);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (20, 2);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (21, 1);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (22, 2);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (23, 3);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (24, 3);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (25, 2);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (26, 2);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (27, 1);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (28, 1);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (29, 3);
INSERT INTO goods_providers (goods_id, provider_id) VALUES (30, 1);